timezones = (
    {"value": "UTC", "label": "UTC"},
    {"value": "America/New_York", "label": "America/New_York"},
    {"value": "America/Chicago", "label": "America/Chicago"},
    {"value": "America/Denver", "label": "America/Denver"},
    {"value": "America/Los_Angeles", "label": "America/Los_Angeles"},
    {"value": "America/Toronto", "label": "America/Toronto"},
    {"value": "America/Mexico_City", "label": "America/Mexico_City"},
    {"value": "America/Sao_Paulo", "label": "America/Sao_Paulo"},
    {"value": "Europe/London", "label": "Europe/London"},
    {"value": "Europe/Berlin", "label": "Europe/Berlin"},
    {"value": "Europe/Paris", "label": "Europe/Paris"},
    {"value": "Europe/Istanbul", "label": "Europe/Istanbul"},
    {"value": "Europe/Moscow", "label": "Europe/Moscow"},
    {"value": "Asia/Dubai", "label": "Asia/Dubai"},
    {"value": "Asia/Karachi", "label": "Asia/Karachi"},
    {"value": "Asia/Kolkata", "label": "Asia/Kolkata"},
    {"value": "Asia/Dhaka", "label": "Asia/Dhaka"},
    {"value": "Asia/Bangkok", "label": "Asia/Bangkok"},
    {"value": "Asia/Shanghai", "label": "Asia/Shanghai"},
    {"value": "Asia/Tokyo", "label": "Asia/Tokyo"},
    {"value": "Asia/Seoul", "label": "Asia/Seoul"},
    {"value": "Australia/Sydney", "label": "Australia/Sydney"},
    {"value": "Pacific/Auckland", "label": "Pacific/Auckland"},
    {"value": "Africa/Cairo", "label": "Africa/Cairo"},
    {"value": "Africa/Johannesburg", "label": "Africa/Johannesburg"},
    {"value": "America/Buenos_Aires", "label": "America/Buenos_Aires"},
    {"value": "America/Lima", "label": "America/Lima"},
    {"value": "Asia/Jerusalem", "label": "Asia/Jerusalem"},
    {"value": "Asia/Beirut", "label": "Asia/Beirut"},
    {"value": "Asia/Tehran", "label": "Asia/Tehran"}
)


languages = [
    {"value": "en-US", "label": "English (US)"},
    {"value": "zh-CN", "label": "Chinese (Simplified)"},
    {"value": "es-ES", "label": "Spanish (Spain)"},
    {"value": "hi-IN", "label": "Hindi"},
    {"value": "ar-SA", "label": "Arabic (Saudi Arabia)"},
    {"value": "bn-BD", "label": "Bengali (Bangladesh)"},
    {"value": "pt-BR", "label": "Portuguese (Brazil)"},
    {"value": "ru-RU", "label": "Russian (Russia)"},
    {"value": "ja-JP", "label": "Japanese"},
    {"value": "de-DE", "label": "German (Germany)"},
    {"value": "fr-FR", "label": "French (France)"},
    {"value": "id-ID", "label": "Indonesian"},
    {"value": "tr-TR", "label": "Turkish (Turkey)"},
    {"value": "ko-KR", "label": "Korean (South Korea)"},
    {"value": "vi-VN", "label": "Vietnamese (Vietnam)"},
    {"value": "it-IT", "label": "Italian (Italy)"},
    {"value": "pl-PL", "label": "Polish (Poland)"},
    {"value": "uk-UA", "label": "Ukrainian (Ukraine)"},
    {"value": "ro-RO", "label": "Romanian (Romania)"},
    {"value": "nl-NL", "label": "Dutch (Netherlands)"},
]
